// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5AzkbwYeFQvtp_P2OamkEuLj1sd01Bt4',
    appId: '1:334765493163:android:df253ca8b7f7baebd120ee',
    messagingSenderId: '334765493163',
    projectId: 'bacakomik-koidevz',
    storageBucket: 'bacakomik-koidevz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV6JAB7fEmevVRPRjChNGRT81o21UTLuk',
    appId: '1:334765493163:ios:31b146f89abfc079d120ee',
    messagingSenderId: '334765493163',
    projectId: 'bacakomik-koidevz',
    storageBucket: 'bacakomik-koidevz.appspot.com',
    androidClientId: '334765493163-and47m3qcef9jtsmva81jasf6qrvo7m6.apps.googleusercontent.com',
    iosClientId: '334765493163-b3e1hkbfm43j79fgd21gredfksuad0hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacakomikApp',
  );
}
